title: Blog of baseball
author: Keith Heffington
email: dransiktolkien@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about baseball and the many things 
  baseball is about. Teams, players, and rules.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
